title = "helios-root"
port = "10010"
log_level_info = "./log/go_helios_da.log"
log_level_err = "./log/go_helios_da_err.log"
[helios_init_config]
    title = "helios_init_conf"
    update_time = 300
[helios_init_config.index_conf]
    [helios_init_config.index_conf.music]
        conf = "./da_conf/search/music_download.conf"
        data_conf = "./da_conf/search/music_download_data.conf"
    [helios_init_config.index_conf.test]
        conf = "./da_conf/search/test_t.conf"
        data_conf = "./da_conf/search/test_t_data.conf"
