title = "helios-root"
[helios_init_config]
    title = "helios_init_conf"
    update_time = 5
[helios_init_config.index_conf]
    [helios_init_config.index_conf.music]
        conf = "./da_conf/search/music_download.conf"
        data_conf = "./da_conf/search/music_download_data.conf"
    [helios_init_config.index_conf.test]
        conf = "./da_conf/search/test_t.conf"
        data_conf = "./da_conf/search/test_t_data.conf"
